// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function make(param) {
  return React.createElement("div", undefined, "Hello Master");
}

var $$default = make;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
