// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Link from "next/link";
import * as NavStyles$MyBlog from "./NavStyles.bs.js";

function Navbar(Props) {
  var match = React.useReducer((function (state, action) {
          return /* record */[/* menuIsActive */!state[/* menuIsActive */0]];
        }), /* record */[/* menuIsActive */false]);
  var dispatch = match[1];
  var state = match[0];
  return React.createElement("div", {
              className: "hero-head"
            }, React.createElement("nav", {
                  className: NavStyles$MyBlog.topnavStyles,
                  id: "topnav"
                }, React.createElement("div", {
                      className: "container"
                    }, React.createElement("div", {
                          className: NavStyles$MyBlog.navbarBrand
                        }, React.createElement(Link.default, {
                              href: "/",
                              children: React.createElement("a", {
                                    className: NavStyles$MyBlog.subtitle
                                  }, "Marcell Ciszek")
                            }), React.createElement("span", {
                              className: NavStyles$MyBlog.navbarBurger(state[/* menuIsActive */0]),
                              onClick: (function (_event) {
                                  return Curry._1(dispatch, /* ToggleMenu */0);
                                })
                            }, React.createElement("span", undefined), React.createElement("span", undefined), React.createElement("span", undefined))), React.createElement("div", {
                          className: NavStyles$MyBlog.navbarMenu(state[/* menuIsActive */0]),
                          id: "navbarMenu"
                        }, React.createElement("div", {
                              className: "navbar-end"
                            }, React.createElement("div", {
                                  className: NavStyles$MyBlog.navbarItem
                                }, React.createElement(Link.default, {
                                      href: "/about",
                                      children: React.createElement("a", undefined, "About")
                                    })), React.createElement("div", {
                                  className: NavStyles$MyBlog.navbarItem
                                }, React.createElement(Link.default, {
                                      href: "/contact",
                                      children: React.createElement("a", undefined, "contact")
                                    })))))));
}

var make = Navbar;

export {
  make ,
  
}
/* react Not a pure module */
